// Code generated by protoc-gen-go. DO NOT EDIT.
// source: discount.proto

/*
Package discount is a generated protocol buffer package.

It is generated from these files:
	discount.proto

It has these top-level messages:
	GetDiscountRequest
	GetDiscountResponse
*/
package discount

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// productID used to represent a product. Ilustrative only.
type GetDiscountRequest struct {
	ProductID int32 `protobuf:"varint,1,opt,name=productID" json:"productID,omitempty"`
}

func (m *GetDiscountRequest) Reset()                    { *m = GetDiscountRequest{} }
func (m *GetDiscountRequest) String() string            { return proto.CompactTextString(m) }
func (*GetDiscountRequest) ProtoMessage()               {}
func (*GetDiscountRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetDiscountRequest) GetProductID() int32 {
	if m != nil {
		return m.ProductID
	}
	return 0
}

// The discount percentage is a fixed value.
type GetDiscountResponse struct {
	Percentage float32 `protobuf:"fixed32,1,opt,name=percentage" json:"percentage,omitempty"`
}

func (m *GetDiscountResponse) Reset()                    { *m = GetDiscountResponse{} }
func (m *GetDiscountResponse) String() string            { return proto.CompactTextString(m) }
func (*GetDiscountResponse) ProtoMessage()               {}
func (*GetDiscountResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetDiscountResponse) GetPercentage() float32 {
	if m != nil {
		return m.Percentage
	}
	return 0
}

func init() {
	proto.RegisterType((*GetDiscountRequest)(nil), "discount.GetDiscountRequest")
	proto.RegisterType((*GetDiscountResponse)(nil), "discount.GetDiscountResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Discount service

type DiscountClient interface {
	GetDiscount(ctx context.Context, in *GetDiscountRequest, opts ...grpc.CallOption) (*GetDiscountResponse, error)
}

type discountClient struct {
	cc *grpc.ClientConn
}

func NewDiscountClient(cc *grpc.ClientConn) DiscountClient {
	return &discountClient{cc}
}

func (c *discountClient) GetDiscount(ctx context.Context, in *GetDiscountRequest, opts ...grpc.CallOption) (*GetDiscountResponse, error) {
	out := new(GetDiscountResponse)
	err := grpc.Invoke(ctx, "/discount.Discount/GetDiscount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Discount service

type DiscountServer interface {
	GetDiscount(context.Context, *GetDiscountRequest) (*GetDiscountResponse, error)
}

func RegisterDiscountServer(s *grpc.Server, srv DiscountServer) {
	s.RegisterService(&_Discount_serviceDesc, srv)
}

func _Discount_GetDiscount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiscountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscountServer).GetDiscount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discount.Discount/GetDiscount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscountServer).GetDiscount(ctx, req.(*GetDiscountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Discount_serviceDesc = grpc.ServiceDesc{
	ServiceName: "discount.Discount",
	HandlerType: (*DiscountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDiscount",
			Handler:    _Discount_GetDiscount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "discount.proto",
}

func init() { proto.RegisterFile("discount.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 148 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0xc9, 0x2c, 0x4e,
	0xce, 0x2f, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0x8c,
	0xb8, 0x84, 0xdc, 0x53, 0x4b, 0x5c, 0xa0, 0xdc, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21,
	0x19, 0x2e, 0xce, 0x82, 0xa2, 0xfc, 0x94, 0xd2, 0xe4, 0x12, 0x4f, 0x17, 0x09, 0x46, 0x05, 0x46,
	0x0d, 0xd6, 0x20, 0x84, 0x80, 0x92, 0x29, 0x97, 0x30, 0x8a, 0x9e, 0xe2, 0x82, 0xfc, 0xbc, 0xe2,
	0x54, 0x21, 0x39, 0x2e, 0xae, 0x82, 0xd4, 0xa2, 0xe4, 0xd4, 0xbc, 0x92, 0xc4, 0xf4, 0x54, 0xb0,
	0x2e, 0xa6, 0x20, 0x24, 0x11, 0xa3, 0x08, 0x2e, 0x0e, 0x98, 0x1e, 0x21, 0x1f, 0x2e, 0x6e, 0x24,
	0x23, 0x84, 0x64, 0xf4, 0xe0, 0x0e, 0xc4, 0x74, 0x8d, 0x94, 0x2c, 0x0e, 0x59, 0x88, 0xbd, 0x4a,
	0x0c, 0x49, 0x6c, 0x60, 0x5f, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xe3, 0xff, 0xd0, 0x70,
	0xe7, 0x00, 0x00, 0x00,
}
